### ISSUE TITLE
Parameter type ignored by ApiExplorer or Swagger

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/Swagger-for-ServiceComposer-Playground#1]
Thanks firstly for advancing the discussion.

I thought I'd try out a post request and whilst I can indeed get a Form binding source parameter working I noticed the parameter's type would only show up as `string`.  Looking at the initial Get request sample and that also appears to show as a `string` type even though it is described as an `int`.  I didn't play much with it as there didn't appear to be much we could do other than setting the Type property.

**Comment by mauroservienti** [comment]
I noticed that too, I did a quick google search with no luck. I'll keep this open to remind me to further investigate.

**Comment by mauroservienti** [comment]
Fixed by https://github.com/ServiceComposer/Swagger-for-ServiceComposer-Playground/commit/d2a326af3dbfbae0d9f41596c37c269a84b44fb3
